name: Test Release Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  TestRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ks_auth_app_id }}
          private_key: ${{ secrets.ks_auth_app_secret }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Modify README.md
        run: |
          # Example command to modify README.md
          echo "This is an automated update" >> README.md

      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Auto-update README.md"
          git push
